import { JetBrains_Mono } from 'next/font/google';
import Header from '@/components/header';
import Footer from '@/components/footer';
import './globals.css';
import type { Metadata } from 'next';

// // 等宽字体(用于代码、数字等)
const jetBrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.className} flex min-h-dvh w-screen flex-col antialiased`}
      >
        <header className="h-[var(--header-height)]">
          <Header />
        </header>
        <main className="flex-1">{children}</main>
        <footer className="h-[var(--footer-height)]">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
